INSERT INTO categorias (nombre,descripcion,estado,fecha_creacion) VALUES ('Útiles de oficina','Papelería y útiles de escritorio',1,CURRENT_TIMESTAMP);
git statusINSERT INTO categorias (nombre,descripcion,estado,fecha_creacion) VALUES ('Limpieza','Artículos de limpieza e higiene',1,CURRENT_TIMESTAMP);
INSERT INTO categorias (nombre,descripcion,estado,fecha_creacion) VALUES ('Tecnología','Suministros y periféricos',1,CURRENT_TIMESTAMP);
INSERT INTO productos (codigo,nombre,costo_unitario,stock,stock_minimo,estado,categoria_id,fecha_creacion) SELECT 'OFI-001','Papel bond A4 x 500 hojas',18.50,120,20,1,id,CURRENT_TIMESTAMP FROM categorias WHERE nombre='Útiles de oficina';
INSERT INTO productos (codigo,nombre,costo_unitario,stock,stock_minimo,estado,categoria_id,fecha_creacion) SELECT 'OFI-002','Lapicero azul caja x 12',9,40,10,1,id,CURRENT_TIMESTAMP FROM categorias WHERE nombre='Útiles de oficina';
INSERT INTO productos (codigo,nombre,costo_unitario,stock,stock_minimo,estado,categoria_id,fecha_creacion) SELECT 'OFI-003','Archivador de palanca',7.5,5,10,1,id,CURRENT_TIMESTAMP FROM categorias WHERE nombre='Útiles de oficina';
INSERT INTO productos (codigo,nombre,costo_unitario,stock,stock_minimo,estado,categoria_id,fecha_creacion) SELECT 'OFI-004','Engrapadora metálica',22,0,5,1,id,CURRENT_TIMESTAMP FROM categorias WHERE nombre='Útiles de oficina';
INSERT INTO productos (codigo,nombre,costo_unitario,stock,stock_minimo,estado,categoria_id,fecha_creacion) SELECT 'LIM-001','Detergente industrial 1 kg',12,60,15,1,id,CURRENT_TIMESTAMP FROM categorias WHERE nombre='Limpieza';
INSERT INTO productos (codigo,nombre,costo_unitario,stock,stock_minimo,estado,categoria_id,fecha_creacion) SELECT 'LIM-002','Papel higiénico x 24',45,10,8,1,id,CURRENT_TIMESTAMP FROM categorias WHERE nombre='Limpieza';
INSERT INTO productos (codigo,nombre,costo_unitario,stock,stock_minimo,estado,categoria_id,fecha_creacion) SELECT 'LIM-003','Lejía 1 L',8,0,5,1,id,CURRENT_TIMESTAMP FROM categorias WHERE nombre='Limpieza';
INSERT INTO productos (codigo,nombre,costo_unitario,stock,stock_minimo,estado,categoria_id,fecha_creacion) SELECT 'LIM-004','Guantes de limpieza',15,25,5,0,id,CURRENT_TIMESTAMP FROM categorias WHERE nombre='Limpieza';
INSERT INTO productos (codigo,nombre,costo_unitario,stock,stock_minimo,estado,categoria_id,fecha_creacion) SELECT 'TEC-001','Tóner HP 105A',180,12,4,1,id,CURRENT_TIMESTAMP FROM categorias WHERE nombre='Tecnología';
INSERT INTO productos (codigo,nombre,costo_unitario,stock,stock_minimo,estado,categoria_id,fecha_creacion) SELECT 'TEC-002','Mouse óptico USB',25,30,10,1,id,CURRENT_TIMESTAMP FROM categorias WHERE nombre='Tecnología';
INSERT INTO productos (codigo,nombre,costo_unitario,stock,stock_minimo,estado,categoria_id,fecha_creacion) SELECT 'TEC-003','Teclado USB',38,3,5,1,id,CURRENT_TIMESTAMP FROM categorias WHERE nombre='Tecnología';
INSERT INTO productos (codigo,nombre,costo_unitario,stock,stock_minimo,estado,categoria_id,fecha_creacion) SELECT 'TEC-004','Cable HDMI 2 m',20,15,5,1,id,CURRENT_TIMESTAMP FROM categorias WHERE nombre='Tecnología';
INSERT INTO areas (codigo,nombre,responsable,email,presupuesto_mensual,estado,fecha_creacion) VALUES ('AR01','Secretaría Académica','Lucía Ramos','secretaria@stockandes.pe',1500,1,CURRENT_TIMESTAMP);
INSERT INTO areas (codigo,nombre,responsable,email,presupuesto_mensual,estado,fecha_creacion) VALUES ('AR02','Laboratorio de Cómputo','Pedro Salas','laboratorio@stockandes.pe',2500,1,CURRENT_TIMESTAMP);
INSERT INTO areas (codigo,nombre,responsable,email,presupuesto_mensual,estado,fecha_creacion) VALUES ('AR03','Biblioteca','Rosa Ticona','biblioteca@stockandes.pe',800,1,CURRENT_TIMESTAMP);
INSERT INTO areas (codigo,nombre,responsable,email,presupuesto_mensual,estado,fecha_creacion) VALUES ('AR04','Mantenimiento','Julio Pari','mantenimiento@stockandes.pe',1000,0,CURRENT_TIMESTAMP);
INSERT INTO areas (codigo,nombre,responsable,email,presupuesto_mensual,estado,fecha_creacion) VALUES ('AR05','Administración','Ana Quispe','administracion@stockandes.pe',1800,1,CURRENT_TIMESTAMP);
INSERT INTO areas (codigo,nombre,responsable,email,presupuesto_mensual,estado,fecha_creacion) VALUES ('AR06','Bienestar Estudiantil','Luis Flores','bienestar@stockandes.pe',1200,1,CURRENT_TIMESTAMP);
COMMIT;
